'use client';

import { useState, useCallback } from 'react';

interface ShareableSignatureCardProps {
  /** Archetype name, e.g. "Strategic Optimist" */
  name: string;
  /** Tagline, e.g. "You see the path AND the light at the end of it." */
  tagline: string;
  /** Two ray names, e.g. ["Intention", "Joy"] */
  rays: [string, string];
  /** Neon accent color from archetype data */
  neonColor?: string;
  /** Identity code, e.g. "CLARITY. WARMTH. MOTION." */
  identityCode?: string;
  /** Optional className override */
  className?: string;
}

/**
 * ShareableSignatureCard — Renders a real server-generated PNG image
 * of the user's Light Signature, optimized for Instagram Stories.
 *
 * The image is generated by /api/og/signature (server-side, no html2canvas).
 * Share button downloads or shares the actual PNG file.
 */
export default function ShareableSignatureCard({
  name,
  tagline,
  rays,
  neonColor = '#F8D011',
  identityCode,
  className = '',
}: ShareableSignatureCardProps) {
  const [sharing, setSharing] = useState(false);

  /** Build the OG image URL with query params */
  const imageUrl = `/api/og/signature?${new URLSearchParams({
    name,
    tagline,
    ray1: rays[0],
    ray2: rays[1],
    neonColor,
    ...(identityCode ? { identityCode } : {}),
    format: 'story',
  }).toString()}`;

  const handleShare = useCallback(async () => {
    setSharing(true);
    try {
      // Fetch the real server-generated PNG
      const res = await fetch(imageUrl);
      const blob = await res.blob();
      const file = new File([blob], 'light-signature.png', { type: 'image/png' });

      // Try native share (mobile)
      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        await navigator.share({
          title: `My Light Signature: ${name}`,
          text: tagline,
          files: [file],
        });
      } else {
        // Fallback: download the PNG
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `light-signature-${name.toLowerCase().replace(/\s+/g, '-')}.png`;
        a.click();
        URL.revokeObjectURL(url);
      }
    } catch {
      // Last resort: copy text
      await navigator.clipboard?.writeText(
        `My Light Signature: ${name}\n${tagline}\n\n143leadership.com`,
      );
    } finally {
      setSharing(false);
    }
  }, [name, tagline, imageUrl]);

  return (
    <div className={`mx-auto max-w-sm ${className}`}>
      {/* Real server-generated card image */}
      <div
        className="overflow-hidden rounded-2xl"
        style={{ border: `1px solid ${neonColor}30` }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={imageUrl}
          alt={`Light Signature card: ${name} — ${rays[0]} + ${rays[1]}`}
          width={1080}
          height={1920}
          className="h-auto w-full"
          loading="lazy"
        />
      </div>

      {/* Share button */}
      <button
        type="button"
        onClick={handleShare}
        disabled={sharing}
        className="btn-secondary mx-auto mt-4 flex items-center gap-2 px-5 py-2.5 text-sm disabled:opacity-50"
        style={{ borderColor: `${neonColor}40`, color: neonColor }}
      >
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8" />
          <polyline points="16 6 12 2 8 6" />
          <line x1="12" y1="2" x2="12" y2="15" />
        </svg>
        {sharing ? 'Generating...' : 'Share My Light Signature'}
      </button>
    </div>
  );
}
